---
name: Asanga Sanjaya  
surname: Abeyaratne
position: "Doctor"
address: "Royal Darwin Hospital"
phone: +61-8-8922-8888
www: mariecurie.com
email: "asaabey@gmail.com"
twitter: mariecurie
github: asaabey
linkedin: asaabey
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::hyndman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(rorcid)
library(tibble)
library(rcrossref)
```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r}
asa_orcid <- "0000-0003-3153-5051"

edu <- rorcid::orcid_educations("0000-0003-3153-5051")

edu$`0000-0003-3153-5051`$`affiliation-group`$summaries[[1]]$`education-summary.organization.name`

```

# Nobel Prizes

```{r}

asa_pubs <- rorcid::orcid_works(asa_orcid)



```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```
